config/routes.rb
Rails.application.routes.draw do
  mount Shoppe::Engine => "/shoppe"

  root :to => "postcards#index"

  get "postcard/:permalink" => "postcards#show", as: "postcard"
  post "postcard/:permalink" => "postcards#buy"
  get "postcard/:permalink" => "postcards#new"
  post "postcard/:permalink" => "postcards#create"
  

  get "basket" => "orders#show"
  delete "basket" => "orders#destroy"

  match "checkout" => "orders#checkout", as: "checkout", via: [:get, :patch]
  match "checkout/pay" => "orders#payment", as: "checkout_payment", via: [:get, :post]
  match "checkout/confirm" => "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]

end

app/models/order.rb
class Order < ActiveRecord::Base
	
end

app/models/postcard.rb
class Postcard < ActiveRecord::Base
belongs_to :category

	def find_congress_people
		# using lat/long get the legislators information... name/district
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_order
    @current_order ||= begin
      if has_order?
        @current_order
      else
        order = Shoppe::Order.create(:ip_address => request.ip)
        session[:order_id] = order.id
        order
      end
    end
  end

  def has_order?
    !!(
      session[:order_id] &&
      @current_order = Shoppe::Order.includes(:order_items => :ordered_item).find_by_id(session[:order_id])
    )
  end

  helper_method :current_order, :has_order?
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def destroy
	  current_order.destroy
	  session[:order_id] = nil
	  redirect_to root_path, :notice => "Basket emptied successfully."
	end

	def update
		@order = current_order.order_items
	end
	
	def checkout
	  @order = Shoppe::Order.find(current_order.id)
	  if request.patch?
	    if @order.proceed_to_confirm(params[:order].permit(:first_name, :last_name, :billing_address1, :billing_address2, :billing_address3, :billing_address4, :billing_country_id, :billing_postcode, :email_address, :phone_number))
	      redirect_to checkout_payment_path
	    end
	   else 
	   	redirect_to checkout_path, :notice => "You forgot something."
	  end
	end

	def payment
	  if request.post?
	    redirect_to checkout_confirmation_path
	  end
	end

	def confirmation
		if request.post?
			current_order.confirm!
			session[:order_id] = nil
			redirect_to root_path, :notice => "Order has been placed! Not technically tho.. this is where the cc gateway comes into play"
		end
	end
end

app/controllers/postcards_controller.rb
class PostcardsController < ApplicationController

	def index
		@postcards = Shoppe::Product.root.ordered.includes(:product_categories, :variants)
		@postcards = @postcards.group_by(&:product_category)
	end

	def show
		@postcard = Shoppe::Product.root.find_by_permalink(params[:permalink])

		congress_people = "https://openstates.org/api/v1/legistators/geo/?lat=35.79&long=-78.78"
		uri = URI.parse(congress_people)
		byebug;
	end

	def new
	   @postcard = Postcard.new
	   if request.xhr?
	     render partial: 'postcards/new', locals: {postcard: @postcard}
	   end
  	end

	def create
		@postcard = Postcard.new(postcard_params)
		if @postcard.save
		  render 'basket'
		  # redirect_to "/films/#{@postcard.review.film.id}"
		else
		  render 'new'
		end
	end

	def buy
	  @postcard = Shoppe::Product.root.find_by_permalink!(params[:permalink])
	  current_order.order_items.add_item(@postcard, 1)
	  redirect_to postcard_path(@postcard.permalink), :notice => "Product has been added successfuly!"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/postcards_helper.rb
module PostcardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PostcardsForProgress</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_order %>
<p style="border:1px solid black;padding:10px;">
  You have <%= pluralize current_order.total_items, 'item'%> in your basket which cost
  <%= number_to_currency current_order.total_before_tax %>.
</p>
<% end %>
<%= link_to "View basket", basket_path %>
<%= flash[:notice] %>

<%= yield %>

</body>
</html>

app/views/orders/_items.html.erb
<table width='100%' border='1'>
  <thead>
    <tr>
      <td>Quantity</td>
      <td>Product</td>
      <td>Sub-Total</td>
      <td>Tax</td>
      <td>Total</td>
    </tr>
  </thead>
  <tbody>
    <% order.order_items.each do |item| %>
    <tr>
      <td><%= item.quantity %></td>
      <td><%= item.ordered_item.full_name %></td>
      <td><%= number_to_currency item.sub_total %></td>
      <td><%= number_to_currency item.tax_amount %></td>
      <td><%= number_to_currency item.total %></td>
    </tr>
    <% end %>

    <% if order.delivery_service %>
    <tr>
      <td></td>
      <td><%= order.delivery_service.name %></td>
      <td><%= number_to_currency order.delivery_price %></td>
      <td><%= number_to_currency order.delivery_tax_amount %></td>
      <td><%= number_to_currency order.delivery_price + order.delivery_tax_amount %></td>
    </tr>
    <% end %>

  </tbody>
  <tfoot>
    <tr>
      <td colspan='4'>Sub-Total</td>
      <td><%= number_to_currency order.total_before_tax %></td>
    </tr>
    <tr>
      <td colspan='4'>Tax</td>
      <td><%= number_to_currency order.tax %></td>
    </tr>
    <tr>
      <td colspan='4'>Total</td>
      <td><%= number_to_currency order.total %></td>
    </tr>
  </tfoot>
</table>

app/views/orders/checkout.html.erb
<h2>Checkout</h2>
<%= render 'items', :order => @order %>

<%= form_for @order, :url => checkout_path do |f| %>
  <dl>
    <dt><%= f.label :first_name, 'Name' %></dt>
    <dd><%= f.text_field :first_name %> <%= f.text_field :last_name %></dd>

    <dt><%= f.label :billing_address1, 'Address' %></dt>
    <dd><%= f.text_field :billing_address1 %></dd>
    <dd><%= f.text_field :billing_address2 %></dd>
    <dd><%= f.text_field :billing_address3 %></dd>
    <dd><%= f.text_field :billing_address4 %></dd>
    <dt><%= f.label :billing_postcode, 'Post code' %></dt>
    <dd><%= f.text_field :billing_postcode %></dd>
    <dd><%= f.collection_select :billing_country_id, Shoppe::Country.ordered, :id, :name, :include_blank => true %></dd>

    <dt><%= f.label :email_address %></dt>
    <dd><%= f.text_field :email_address %></dd>

    <dt><%= f.label :phone_number %></dt>
    <dd><%= f.text_field :phone_number %></dd>

    <dd><%= f.submit 'Continue'%></dd>
  </dl>
<% end %>

app/views/orders/confirmation.html.erb
<h2>Place your order</h2>
<%= render 'items', :order => current_order %>
<%= button_to "Place order" %>

app/views/orders/payment.html.erb
<h2>Make your payment</h2>
<%= form_tag do %>
  <dl>
    <dt><%= label_tag 'card_number' %></dt>
    <dd><%= text_field_tag 'card_number' %></dd>
    <dt><%= label_tag 'expiry' %></dt>
    <dd><%= text_field_tag 'expiry' %></dd>
    <dt><%= label_tag 'security_code' %></dt>
    <dd><%= text_field_tag 'security_code' %></dd>
    <dd><%= submit_tag "Continue" %></dd>
  </dl>
<% end %>

app/views/orders/show.html.erb
<h2>Your basket</h2>

<%= render 'items', :order => current_order %>

<p><%= link_to 'Update Basket', basket_path, :method => :update %></p>
<p><%= link_to 'Empty Basket', basket_path, :method => :delete %></p>
<%= link_to "Checkout", checkout_path %>

app/views/postcards/index.html.erb
<h2>Index page</h2>

<% @postcards.each do |category, postcards| %>
  <h3><%= category.name %></h3>
  <p><%= category.description %></p>
  <ul>
    <% postcards.each do |postcard| %>
    <li>
      <h4><%= link_to postcard.name, postcard_path(postcard.permalink) %></h4>
    </li>
    <% end %>
  </ul>
<% end %>

app/views/postcards/show.html.erb
<h2><%= @postcard.name %></h2>

<% if @postcard.default_image %>
  <%= image_tag @postcard.default_image.path, :width => '200px', :style => "float:right" %>
<% end %>

<h3>Description: <%= @postcard.description %></h3>
<p><b>Price:</b> <%= number_to_currency @postcard.price %></p>
<p>
  <b><%= number_to_currency @postcard.price %></b>
  <%= link_to "Add to basket", postcard_path(@postcard.permalink), :method => :post %>
</p>

<hr>
<%= simple_format @postcard.description %>
<%= @postcard.short_description %>

<!-- not sure how to edit description. ajax/qjuery -->
<hr>

<%= render partial: 'new', locals: {postcard: @postcard} %>

<p><%= link_to "Back to list", root_path %></p>